x-template: &template
  image: joelgarciajr84/rinha-backend-go@sha256:13efc7421cf82d269315cc5465766309a34b0e17fd06c10689250c0ea44d61cc
  platform: linux/amd64
  environment:
    PAYMENT_PROCESSOR_DEFAULT_URL: "http://payment-processor-default:8080"
    PAYMENT_PROCESSOR_FALLBACK_URL: "http://payment-processor-fallback:8080"
    REDIS_URL: "redis:6379"
    PORT: 80
  networks: [backend, payment-processor]
  deploy:
    resources:
      limits:
        cpus: "0.5"
        memory: "115MB"

services:
  galo_01:
    <<: *template
    hostname: galo_01
    restart: unless-stopped
    depends_on: [redis]

  galo_02:
    <<: *template
    hostname: galo_02
    restart: unless-stopped
    depends_on: [redis]

  nginx:
    image: nginx
    platform: linux/amd64
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:80"
    networks: [backend]
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.1"    # <= ajustado
          memory: "65MB" # <= ajustado

  redis:
    image: redis:8.0.3-alpine
    platform: linux/amd64
    networks: [backend]
    ulimits:
      nofile: 262144
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "55MB"
    command:
      - redis-server
      - --save
      - ""
      - --appendonly
      - "no"
      - --maxmemory
      - "48mb"
      - --maxmemory-policy
      - allkeys-lru
      - --latency-monitor-threshold
      - "0"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
